### ISSUE TITLE
the public data set for binary semantic segmentation

### ISSUE THREAD

**Issue by wenouyang** [nightrome/really-awesome-semantic-segmentation#1]
Thanks for maintaining this resource list. For the public available data set, are there any semantic segmentation tasks that involves two classes only? Thanks.

**Comment by nightrome** [comment]
The question is probably whether it is still semantic segmentation if there are only two classes. A lot of applications have one foreground and one background class. These include hand/medical device segmentation, foreground segmentation in surveillance cameras ("background subtraction"), organ segmentation in medical image segmentation etc. 
What exactly are you looking for?

**Comment by wenouyang** [comment]
Hi nightrome, the studied problem is like waterway over the background earth, or organ segmentation in medical images.

**Comment by nightrome** [comment]
Road detection is a pretty common setup (e.g. [KITTI](http://www.cvlibs.net/datasets/kitti/eval_road.php)).
